# DNS Zone Transfer 설정_setup

---
- name: actionlist 15
  hosts: intranetweb
  tasks:

  - set_fact:
      diag: Set specific IPs for zone transfer
      num: 15

  - debug:
      var: diag
  - debug:
      var: num

  # DNS(BIND) 서비스 프로세스 확인
  - name: Check if DNS service (BIND) is running
    shell: ps -ef | grep -v grep | grep named
    register: dns_process
    ignore_errors: yes

  # 서비스가 실행 중인 경우 사용 가능한 서비스 이름 확인
  - name: Get DNS service status
    command: systemctl status named || systemctl status bind9
    register: dns_service_status
    ignore_errors: yes

  # /etc/named.conf 파일에 Zone Transfer 설정 추가
  - name: Set specific IPs for zone transfer in named.conf
    blockinfile:
      path: /etc/named.conf
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      block: |
        options {
            allow-transfer { 10.10.10.111; 10.10.10.112; };
        };
        zone "xxx.co.kr" {
            type master;
            file "db.xxx.co.kr";
            allow-transfer { 10.10.10.111; 10.10.10.112; };
        };
    when: dns_process is defined and dns_process.stdout is defined and dns_process.stdout != ""

  # DNS 서비스를 사용하지 않는 경우 서비스 중지
  - name: Stop DNS service if not in use
    service:
      name: "{{ dns_service_status.stdout | regex_replace('.*: (\\w+).*', '\\1') }}"
      state: stopped
    when: dns_process is defined and dns_process.stdout == ""

  # Zone Transfer 설정 후 메시지 출력
  - name: Notify about zone transfer setting update
    debug:
      msg: "Zone Transfer has been restricted to specific IPs."
    when: dns_process is defined and dns_process.stdout is defined and dns_process.stdout != ""

  # DNS 서비스를 사용하지 않는 경우 메시지 출력
  - name: Notify if DNS service is not in use
    debug:
      msg: >
        {% if dns_process is defined and dns_process.stdout is defined and dns_process.stdout == "" %}
          N/A: DNS service (BIND) is not running, service stopped.
        {% endif %}

  # action result

  - debug:
      msg: 조치완료
  # 조치 결과 디테일 / status는 점검 완료
  - set_fact:
      result: "{{ {'num': num, 'diag': diag, 'details': ['hihi check~ Setting Zone Transfer for specific server and domain is completed'], 'status': 'Action Completed'} }}"
  - copy:
      content: "{{ result }}"
      dest: /home/ubuntu/grbprj/log/linux/action/15.json
    delegate_to: localhost
  - debug:
      var: result
