- hosts: intranetweb
  tasks:
     
    - set_fact:
        diag: Set ownership for docker.service
        num: 13
    - debug:
        var: diag
    - debug:
        var: num
    
    - shell: chown root:root /lib/systemd/system/docker.service

    - block:
        - set_fact:
            result: "{{{'num':num, 'diag':diag, 'details':['Assign ownership to docker.service'], 'status':'Action Completed'}}}"
        - copy:
            content: "{{ result }}"
            dest: "../../log/docker/action/{{num}}.json"
          delegate_to: localhost