- hosts: intranetweb
  tasks:
    - set_fact:
        diag: Remove unnecessary users from the Docker group
        num: 2
    - debug:
        var: diag
    - debug:
        var: num
        
    - shell: "gpasswd -d {item} docker"
      loop: "{{bypass}}"

    - block:
        - set_fact:
            result: "{{{'num':num, 'diag':diag, 'details':['unnecessary users are removed'], 'status':'Action Completed'}}}"
        - copy:
            content: "{{ result }}"
            dest: "../../log/docker/action/{{num}}.json"
          delegate_to: localhost