- hosts: intranetweb
  tasks:
     
    - set_fact:
        diag: Set access permissions for /var/run/docker.sock file
        num: 20
    - debug:
        var: diag
    - debug:
        var: num
        
    - shell: chmod 660 /var/run/docker.sock

    - block:
        - set_fact:
            result: "{{{'num':num, 'diag':diag, 'details':['Configure access permissions for the /var/run/docker.sock file.'], 'status':'Action Completed'}}}"
        - copy:
            content: "{{ result }}"
            dest: "../../log/docker/action/{{num}}.json"
          delegate_to: localhost