- hosts: intranetweb
  tasks:
     
    - set_fact:
        diag: Run containers as a non-root user
        num: 25
    - debug:
        var: diag
    - debug:
        var: num

    - shell: chmod 644 /etc/sysconfig/docker

    - block:
        - set_fact:
            result: "{{{'num':num, 'diag':diag, 'details':['Execute containers using a non-root user.'], 'status':'Action Completed'}}}"
        - copy:
            content: "{{ result }}"
            dest: "../../log/docker/action/{{num}}.json"
          delegate_to: localhost