- hosts: intranetweb
  tasks:
     
    - set_fact:
        diag: Audit /var/lib/docker
        num: 4
    - debug:
        var: diag
    - debug:
        var: num
        
    - lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: '-w /var/lib/docker -k docker'

    - shell: service auditd restart

    - block:
        - set_fact:
            result: "{{{'num':num, 'diag':diag, 'details':['The audit setup is complete'], 'status':'Action Completed'}}}"
        - copy:
            content: "{{ result }}"
            dest: "../../log/docker/action/{{num}}.json"
          delegate_to: localhost