- hosts: intranetweb
  tasks:
    heade
    - set_fact:
        diag: Audit docker.socket
        num: 7
    - debug:
        var: diag
    - debug:
        var: num

    - lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: '-w /lib/systemd/system/docker.socket -k docker'

    - shell: service auditd restart

    - block:
        - set_fact:
            result: "{{{'num':num, 'diag':diag, 'details':['The audit setup is complete'], 'status':'Action Completed'}}}"
        - copy:
            content: "{{ result }}"
            dest: "../../log/docker/action/{{num}}.json"
          delegate_to: localhost