- hosts: intranetweb
  tasks:
    # header
    - set_fact:
        diag: Set ownership for /etc/default/docker
        num: 23
    - debug:
        var: diag
    - debug:
        var: num
    
    # body
    - shell: "stat -c %U:%G /etc/default/docker"
      register: ret
      ignore_errors: true
    
    # weak?
    - set_fact:
        weak: null
      when: ret.stdout | regex_search('No such file or directory') is not none
    
    - set_fact:
        weak: "{{ret.stdout != 'root:root'}}"
      when: ret.stdout | regex_search('No such file or directory') is none
    
    - debug:
        var: weak
    
    - set_fact:
        reason: "{{['/etc/default/docker dees not exist']}}"
      when: weak is none
    
    - set_fact:
        reason: "{{['The owner and group of the /etc/default/docker are not root.']}}"
      when: weak is not none and weak
    
    - set_fact:
        reason: "{{['The owner and group of the /etc/default/docker are root.']}}"
      when: weak is not none and not weak

    - set_fact:
        bypass: null
    - debug:
        var: bypass

    # result
    - block:
        - debug:
            msg: 해당없음
        - copy:
            content: "{{ {'num':num, 'diag':diag, 'weak':none , 'reason':reason, 'bypass':bypass} | to_json }}"
            dest: "../../log/docker/diag/{{num}}.json"
          delegate_to: localhost
      when: weak is none
    
    - block:
        - debug:
            msg: 취약
        - copy:
            content: "{{ {'num':num, 'diag':diag, 'weak':True , 'reason':reason, 'how_action':['Set ownership'], 'bypass':bypass} | to_json }}"
            dest: "../../log/docker/diag/{{num}}.json"
          delegate_to: localhost
      when: weak is not none and weak
    
    - block:
        - debug:
            msg: 양호
        - copy:
            content: "{{ {'num':num, 'diag':diag, 'weak':False , 'reason':reason, 'bypass':bypass} | to_json }}"
            dest: "../../log/docker/diag/{{num}}.json"
          delegate_to: localhost
      when: weak is not none and not weak