# Okay

- name: checklist 3
  hosts: intranetweb
  
  tasks:
  # header
  - set_fact:
      diag: 오류 메세지 설정
      num: 3
  - debug:
      var: diag
  - debug:
      var: num

  # body1
  - name: Find status code and message in error page
    command: docker exec -i expressgrb bash -c "grep -n '{% raw %}{{statusCode}}{% endraw %}' /var/lib/ghost/current/core/server/views/error.hbs"
    register: status_code_lines
    ignore_errors: yes

  # weak?
  - set_fact:
      weak: "{{ status_code_lines.stdout_lines }}"
  - debug:
      var: weak

  # result
  - block:
      - debug:
          msg: 해당없음
      - set_fact:
          result: "{{{'num': num, 'diag': diag, 'weak': none, 'reason': ['N/A']}}}"
      - copy:
          content: "{{ result }}"
          dest: /home/ubuntu/grbprj/log/nodejs/diag/3.json
        delegate_to: localhost
    when: weak is none

  - block:
      - debug:
          msg: 취약
      - set_fact:
          result: "{{{'num': num, 'diag': diag, 'weak': True, 'reason': ['status code and message found in error page'], 'bypass': [{'weak_lines': status_code_lines.stdout}], 'how_action': ['Action will replace error status code and message with unified error message. Do you want to proceed?']}}}"
      - copy:
          content: "{{ result }}"
          dest: /home/ubuntu/grbprj/log/nodejs/diag/3.json
        delegate_to: localhost
    when: weak is not none and weak

  - block:
      - debug:
          msg: 양호
      - set_fact:
          result: "{{{'num': num, 'diag': diag, 'weak': False, 'reason': ['status code and message not found in error page']}}}"
      - copy:
          content: "{{ result }}"
          dest: /home/ubuntu/grbprj/log/nodejs/diag/3.json
        delegate_to: localhost
    when: weak is not none and not weak
