- name: checklist 6
  hosts: intranetweb
  
  tasks:
  # header
  - set_fact:
      diag: 웹 프로세스 제한
      num: 6
  - debug:
      var: diag
  - debug:
      var: num

  # body
  - name: Check Web Process Limit 
    shell: docker exec -i nginxgrb bash -c "ps -ef | grep nginx"
    register: ps_output
    ignore_errors: yes

  - name: Print message and install procps if 'ps' command is not found
    shell: docker exec -i nginxgrb bash -c "apt-get update && apt install procps"
    when: "'command not found' in ps_output.stderr"

  - name: Re-run 'ps -ef | grep nginx' after installing procps
    shell: docker exec -i nginxgrb bash -c "ps -ef | grep nginx"
    when: "'command not found' in ps_output.stderr"
    register: ps_output_after_install
    
  # weak?
  - set_fact:
        weak: "{{ (ps_output | select('search', 'nginx: worker process') | select('search', 'nobody|root') | list) or (ps_output_after_install | select('search', 'nginx: worker process') | select('search', 'nobody|root') | list) }}"
  - debug:
      var: weak

  # result
  - block:
      - debug:
          msg: 해당없음
      - set_fact:
          result: "{{{'num': num, 'diag': diag, 'weak': none, 'reason': ['N/A']} }}"
      - copy:
          content: "{{ result }}"
          dest: /home/ubuntu/grbprj/log/nginx/diag/6.json
        delegate_to: localhost
    when: weak is none

  - block:
      - debug:
          msg: 취약
      - set_fact:
          result: "{{{'num': num, 'diag': diag, 'weak': True, 'reason': ['Web server Daemon is running as root.'], 'bypass': [{}], 'how_action': ['Action will Set Web Process Limit. Do you want to proceed?']} }}"
      - copy:
          content: "{{ result }}"
          dest: /home/ubuntu/grbprj/log/nginx/diag/6.json
        delegate_to: localhost
    when: weak is not none and weak

  - block:
      - debug:
          msg: 양호
      - set_fact:
          result: "{{{'num': num, 'diag': diag, 'weak': False, 'reason': ['Web Server Daemon is not running as root.']} }}"
      - copy:
          content: "{{ result }}"
          dest: /home/ubuntu/grbprj/log/nginx/diag/6.json
        delegate_to: localhost
    when: weak is not none and not weak
  
  - name: Sorting result
    set_fact:
      result: "{{ result | sort(attribute='num') }}"
  - debug:
      var: result