---
- name: checklist 10
  hosts: intranetweb
  
  tasks:

  # header
  - set_fact:
      diag: Set OS_ROLES, REMOTE_OS_ROLES
      num: 10
  - debug:
      var: diag
  - debug:
      var: num

  # body

  - name: OS role check
    shell: echo "show parameter os_roles;" | docker exec -i oraclegrb sqlplus C##grb/dkagh1
    register: result_10
  - name: tab remove
    set_fact:
      clean_output: "{{ result_10.stdout_lines | map('regex_replace', '\\t+', ' ') | list }}"
  - set_fact:
      os_roles_lines: "{{ clean_output | select('search', '^os_roles') }}"
  - set_fact:
      remote_os_roles_lines: "{{ clean_output | select('search', '^remote_os_roles') }}"
  - debug:
      msg: "{{ os_roles_lines }}"
  - debug:
      msg: "{{ remote_os_roles_lines }}"

  - set_fact:
      report: >
        {% set os_roles_lines = clean_output | select('search', '^os_roles\\s') | list %}
        {% set remote_os_roles_lines = clean_output | select('search', '^remote_os_roles\\s') | list %}
        {% if 'FALSE' in os_roles_lines | join(' ') %}
          ok
          {% if 'FALSE' in remote_os_roles_lines | join (' ') %}
            good
          {% else %}
            weak
          {% endif %}
        {% else %}
          weak
        {% endif %}
  - debug:
      msg: "{{ report }}"

  # weak?
  - set_fact:
      weak: "{{ report | regex_search('weak') }}"
  - debug:
      var: weak

  # result
 
  - block:
      - debug:
          msg: 해당없음
      - set_fact:
          result: "{{{'num':num, 'diag':diag, 'weak':none, 'reason':['N/A']}}}"
      - copy:
          content: "{{ result }}"
          dest: "../../log/oracle/diag/{{num}}.json"
        delegate_to: localhost
    when: weak is none

  - block:
      - debug:
          msg: 취약
      - set_fact:
          result: "{{{'num':num, 'diag':diag, 'weak':True, 'reason':['Permissions granted by an OS group not controlled by database access control are allowed.'], 'how_action':['Action will set OS_ROLES and REMOTE_OS_ROLES to FALSE. Do you want to proceed? ']}}}"
      - copy:
          content: "{{ result }}"
          dest: "../../log/oracle/diag/{{num}}.json"
        delegate_to: localhost
    when: weak is not none and weak

  - block:
      - debug:
          msg: 양호
      - set_fact:
          result: "{{{'num':num, 'diag':diag, 'weak':False, 'reason':['Permissions granted by an OS group not controlled by database access control are restricted.']}}}"
      - copy:
          content: "{{ result }}"
          dest: "../../log/oracle/diag/{{num}}.json"
        delegate_to: localhost
    when: weak is not none and not weak
  
 
  - debug:
      var: result