---
- name: checklist 2
  hosts: intranetweb
  
  tasks:
  # header
  - set_fact:
      diag: Remove unnecessary accounts
      num: 2
  - debug:
      var: diag
  - debug:
      var: num

  # body
  # - name: Show user name status-open
  #   shell: echo "select username from DBA_USERS where ACCOUNT_STATUS='OPEN';" | docker exec -i oraclegrb sqlplus C##grb/dkagh1
  #   register: result1
  - name: Last login
    shell: echo "SELECT username FROM dba_users WHERE LAST_LOGIN IS NOT NULL AND EXTRACT(DAY FROM (SYSDATE - last_login)) >= 3;" | docker exec -i oraclegrb sqlplus C##grb/dkagh1
    register: result2
  - set_fact:
      plus_ids: []
  # - name: print lists
  #   debug:
  #     msg: "{{ result1.stdout_lines | reject('search', 'SQL') | reject('search', 'Version') | reject('search', 'SQL') | reject('search', 'Ora') | reject('search', 'Connect') | reject('search', 'Last') | reject('equalto', '') }}"
  - set_fact:
      plus_ids: "{{ result2.stdout_lines | reject('search', 'SQL') | reject('search', 'select') | reject('search', 'Version') | reject('search', 'SQL') | reject('search', 'Ora') | reject('search', 'Connect') | reject('search', 'Last') | reject('equalto', '') | reject('search', 'USERNAME') | reject('search', '---') | map('regex_replace', '\\t+', ' ') }}"
    when: result2.stdout_lines | reject('search', 'SQL') | reject('search', 'select') | reject('search', 'Version') | reject('search', 'SQL') | reject('search', 'Ora') | reject('search', 'Connect') | reject('search', 'Last') | reject('equalto', '') | reject('search', 'USERNAME') | reject('search', '---') | map('regex_replace', '\\t+', ' ') | reject('equalto', 'SYSTEM') | reject('equalto', 'SYS') | length > 0
  #| reject('equalto', 'SYSTEM') | reject('equalto', 'SYS') 이거 있는게 양호인거임
  - set_fact:
      weak_ids: []
  - set_fact:
      weak_ids: "{{ weak_ids + plus_ids }}"
  - debug:
      msg: "{{ plus_ids }}"
  - debug:
      msg: "{{ weak_ids }}"

  # weak?
  - set_fact:
      weak: "{{ weak_ids != [] }}"
  - debug:
      var: weak
 
  # result
 
  - block:
      - debug:
          msg: 해당없음
      - set_fact:
          result: "{{{'num':num, 'diag':diag, 'weak':none, 'reason':['N/A']}}}"
      - copy:
          content: "{{ result }}"
          dest: "../../log/oracle/diag/{{num}}.json"
        delegate_to: localhost
    when: weak is none

  - block:
      - debug:
          msg: 취약
      - set_fact:
          result: "{{{'num':num, 'diag':diag, 'weak':True, 'reason':[weak_ids | join(', ') + ' is 3 days over since login '], 'bypass':[{'weak_ids':weak_ids}], 'how_action':[' Action will delete the '+weak_ids | join(', ')+' account. Do you want to proceed? ']}}}"
      - copy:
          content: "{{ result }}"
          dest: "../../log/oracle/diag/{{num}}.json"
        delegate_to: localhost
    when: weak is not none and weak

  - block:
      - debug:
          msg: 양호
      - set_fact:
          result: "{{{'num':num, 'diag':diag, 'weak':False, 'reason':['no accounts inactive for over 3 days']}}}"
      - copy:
          content: "{{ result }}"
          dest: "../../log/oracle/diag/{{num}}.json"
        delegate_to: localhost
    when: weak is not none and not weak
  
 
  - debug:
      var: result
  