---
- name: checklist 5
  hosts: intranetweb
  
  tasks:

  # header
  - set_fact:
      diag: Restrict remote access to the DB server
      num: 5
  - debug:
      var: diag
  - debug:
      var: num

  # body

  - name: remote_os_authent
    shell: echo "SELECT NAME, VALUE, DISPLAY_VALUE, ISDEFAULT FROM V\$PARAMETER WHERE NAME = 'remote_os_authent';" | docker exec -i oraclegrb sqlplus C##grb/dkagh1
    register: result1
  - name: version
    shell: echo "select banner from V\$version;" | docker exec -i oraclegrb sqlplus C##grb/dkagh1
    register: result2
  # - name: print exist or not
  #   debug:
  #     msg: "{{ result1 }}"
  # - name: print version
  #   debug:
  #     msg: "{{ result2 }}"
  # - name: print is it Weak or Not
  #   debug:
  #     msg: >
  #       {% if 'no rows selected' in result1.stdout %}
  #         check version
  #         {% if 'Version 13' in result2.stdout or 'Version 16' in result2.stdout or 'Version 19' in result2.stdout or 'Version 21' in result2.stdout or 'Version 23' in result2.stdout %}
  #           {{ result2.stdout_lines | reject('search', 'SQL') | reject('search', 'SQL') | reject('search', 'Ora') | reject('search', 'Connect') | reject('search', 'Last') | reject('equalto', '') }} 
  #           it is ok
  #         {% endif %}
  #       {% else %}
  #         Weak
  #       {% endif %}

  # weak?
  - set_fact:
      weak: "{{ 'no rows selected' not in result1.stdout or ('Version 13' not in result2.stdout and 'Version 16' not in result2.stdout and 'Version 19' not in result2.stdout and 'Version 21' not in result2.stdout and 'Version 23' not in result2.stdout) }}"
  - debug:
      var: weak

  # result
 
  - block:
      - debug:
          msg: 해당없음
      - set_fact:
          result: "{{{'num':num, 'diag':diag, 'weak':none, 'reason':['N/A']}}}"
      - copy:
          content: "{{ result }}"
          dest: "../../log/oracle/diag/{{num}}.json"
        delegate_to: localhost
    when: weak is none

  - block:
      - debug:
          msg: 취약
      - set_fact:
          result: "{{{'num':num, 'diag':diag, 'weak':True, 'reason':['Remote OS authentication is enabled.'], 'how_action':[' Action will restrict remote OS authentication. Do you want to proceed? ']}}}"
      - copy:
          content: "{{ result }}"
          dest: "../../log/oracle/diag/{{num}}.json"
        delegate_to: localhost
    when: weak is not none and weak

  - block:
      - debug:
          msg: 양호
      - set_fact:
          result: "{{{'num':num, 'diag':diag, 'weak':False, 'reason':['The remote_os_authent parameter does not exist, and Oracle no longer permits remote OS authentication starting from version 12c, and this version is higher']}}}"
      - copy:
          content: "{{ result }}"
          dest: "../../log/oracle/diag/{{num}}.json"
        delegate_to: localhost
    when: weak is not none and not weak
  
 
  - debug:
      var: result