---
- name: checklist 10
  hosts: intranetweb
  
  tasks:

  # header
  - set_fact:
      diag: Set OS_ROLES, REMOTE_OS_ROLES
      num: 10
  - debug:
      var: diag
  - debug:
      var: num

  # action result
 
  - debug:
      msg: 조치완료
  # 조치 결과 디테일 / status는 점검 완료
  - set_fact:
      result: "{{{'num':num, 'diag':diag, 'details':['Setting OS_ROLES and REMOTE_OS_ROLES to FALSE has been completed.'], 'status':'Action Completed'}}}"
  - copy:
      content: "{{ result }}"
      dest: "../../log/oracle/action/{{num}}.json"
    delegate_to: localhost
  - debug:
      var: result


  - name: OS_ROLE
    shell: echo "ALTER SYSTEM SET OS_ROLES=FALSE SCOPE=spfile;" | docker exec -i oraclegrb sqlplus C##grb/dkagh1