---
- name: checklist 12
  hosts: intranetweb
  tasks:

  # header
  - set_fact:
      diag: Enable logging
      num: 12
  - debug:
      var: diag
  - debug:
      var: num
  
  # action result
 
  - debug:
      msg: 조치완료
  # 조치 결과 디테일 / status는 점검 완료
  - set_fact:
      result: "{{{'num':num, 'diag':diag, 'details':['The application of the audit log storage policy for the DBMS has been completed.'], 'status':'Action Completed'}}}"
  - copy:
      content: "{{ result }}"
      dest: "../../log/oracle/action/{{num}}.json"
    delegate_to: localhost
  - debug:
      var: result

  - name: logging policy setting
    shell: echo "ALTER SYSTEM SET audit_trail=DB SCOPE=SPFILE;" | docker exec -i oraclegrb sqlplus C##grb/dkagh1