---
- name: actionlist 3
  hosts: intranetweb
  tasks:
  # 명령어는 이거임 ansible-playbook actionlists/2.yml -e '{"bypass": [{"weak_ids": ["SYSTEM"], "test": "testyo"}]}'
  - set_fact:
      diag: 링크 사용 금지
      num: 3
  - debug:
      var: diag
  - debug:
      var: num

  - name: Insert disable_symlinks off; into nginx.conf inside nginxgrb container
    shell: |
      docker exec -i nginxgrb bash -c "sed -i '/http {/a\    disable_symlinks off;' /etc/nginx/nginx.conf"
  - name: Check the result 
    shell: docker exec -i nginxgrb bash -c "cat /etc/nginx/nginx.conf"
    register: check_the_result   
    
  # action result
  - set_fact:
      detail_description: "Disable symlinks off Setting Successful."
      msg: 조치완료
  # 조치 결과 디테일 / status는 점검 완료
  - set_fact:
      result: "{{{'num':num, 'diag':diag, 'details':[detail_description, check_the_result.stdout_lines], 'status':'Action Completed'}}}"
  - copy:
      content: "{{ result }}"
      dest: /home/ubuntu/grbprj/log/nginx/action/3.json
    delegate_to: localhost
  - debug:
      var: result
