---
- name: actionlist 4
  hosts: intranetweb
  tasks:
  # 명령어는 이거임 ansible-playbook actionlists/2.yml -e '{"bypass": [{"weak_ids": ["SYSTEM"], "test": "testyo"}]}'
  - set_fact:
      diag: 파일 업로드 및 다운로드 제한
      num: 4
  - debug:
      var: diag
  - debug:
      var: num

  - name: Insert client_max_body_size into nginx.conf 
    shell: |
      docker exec -i nginxgrb bash -c "sed -i '/http {/a\    client_max_body_size 20M;' /etc/nginx/nginx.conf"
  - name: Check the result 
    shell: docker exec -i nginxgrb bash -c "cat /etc/nginx/nginx.conf"
    register: check_the_result   

  # action result
  - set_fact:
      detail_description: "Set File Upload & Download Limit Successful."
      msg: 조치완료
  # 조치 결과 디테일 / status는 점검 완료
  - set_fact:
      result: "{{{'num':num, 'diag':diag, 'details':[detail_description, check_the_result.stdout_lines], 'status':'Action Completed'}}}"
  - copy:
      content: "{{ result }}"
      dest: /home/ubuntu/grbprj/log/nginx/action/4.json
    delegate_to: localhost
  - debug:
      var: result
