# 계정 잠금 임계값 설정_check
---
- name: checklist 3
  hosts: intranetweb
  tasks: 
# header
      
  - set_fact:
      diag: Check account lockout threshold settings
      num: 3
    
  - debug:
      var: diag
  - debug:
      var: num

# body
  - name: Check deny setting in /etc/pam.d/system-auth
    shell: cat /etc/pam.d/system-auth | grep deny
    register: system_auth_deny
    ignore_errors: yes

  - name: Check deny setting in /etc/pam.d/password-auth
    shell: cat /etc/pam.d/password-auth | grep deny
    register: password_auth_deny
    ignore_errors: yes

# checking weak
  - set_fact:
      weak: >
        {{ 
          (system_auth_deny.stdout is search('deny=[0-5]') == False) and
          (password_auth_deny.stdout is search('deny=[0-5]') == False) 
        }}
      
  - debug:
      var: weak

# result 
  - block:
      - debug:
          msg: 해당없음
      - set_fact:
          result: "{{ {'num': num, 'diag': diag, 'weak': none, 'reason': ['N/A']} }}"
      - copy:
          content: "{{ result | to_nice_json }}"
          dest: /home/ubuntu/grbprj/log/linux/diag/3.json
        delegate_to: localhost
    when: weak is none

  - block:
      - debug:
          msg: 취약
      - set_fact:
          result: "{{ {'num': num, 'diag': diag, 'weak': True, 'reason': ['Account lockout threshold is set to more than 5 attempts'], 'bypass': [{'reason':'Account lockout threshold exceeded 5 attempts'}], 'how_action': ['Action will set account lockout threshold to 5 attempts. Do you want to proceed?']} }}"
      - copy:
          content: "{{ result | to_nice_json }}"
          dest: /home/ubuntu/grbprj/log/linux/diag/3.json
        delegate_to: localhost
    when: weak is not none and weak

  - block:
      - debug:
          msg: 양호
      - set_fact:
          result: "{{ {'num': num, 'diag': diag, 'weak': False, 'reason': ['The account lockout threshold is set to 5 times or less']} }}"
      - copy:
          content: "{{ result | to_nice_json }}"
          dest: /home/ubuntu/grbprj/log/linux/diag/3.json
        delegate_to: localhost
    when: weak is not none and not weak

