# root 홈, 디렉터리 권한패스 설정_check
---
- name: checklist 5
  hosts: intranetweb
  tasks: 
# header
      
  - set_fact:
      diag: Check root home and path directory permission settings
      num: 5
    
  - debug:
      var: diag
  - debug:
      var: num

# body
  - name: Check current PATH for root
    command: echo $PATH
    register: current_path

# checking weak
  - set_fact:
      weak: "{{ current_path.stdout.startswith('.') or ':.' in current_path.stdout }}"
    
  - debug:
      var: weak

# result
  - block:
      - debug:
          msg: 해당없음
      - set_fact:
          result: "{{ {'num': num, 'diag': diag, 'weak': none, 'reason': ['N/A']} }}"
      - copy:
          content: "{{ result | to_nice_json }}"
          dest: /home/ubuntu/grbprj/log/linux/diag/5.json
        delegate_to: localhost
    when: weak is none

  - block:
      - debug:
          msg: 취약
      - set_fact:
          result: "{{ {'num': num, 'diag': diag, 'weak': True, 'reason': ['PATH for root contains . at the front or middle'], 'how_action': ['Action will remove the . in PATH from the front or middle. Do you want to proceed?']} }}"
      - copy:
          content: "{{ result | to_nice_json }}"
          dest: /home/ubuntu/grbprj/log/linux/diag/5.json
        delegate_to: localhost
    when: weak is not none and weak

  - block:
      - debug:
          msg: 양호
      - set_fact:
          result: "{{ {'num': num, 'diag': diag, 'weak': False, 'reason': ['The PATH for root does not have a dot (.) at the front or middle']} }}"
      - copy:
          content: "{{ result | to_nice_json }}"
          dest: /home/ubuntu/grbprj/log/linux/diag/5.json
        delegate_to: localhost
    when: weak is not none and not weak

