# 파일 및 디렉터리 소유자 설정_check
---
- name: checklist 6
  hosts: intranetweb
  tasks:
    # header
      
    - set_fact:
        diag: Check for files and directories with no owner or group
        num: 6
    
    - debug:
        var: diag
    - debug:
        var: num

    # body
    - name: Find files and directories with no user or group
      shell: 'find /etc /tmp /bin /sbin \( -nouser -o -nogroup \) -xdev -exec ls -al {} \; 2> /dev/null'
      register: unowned_files

    # checking weak
    - set_fact:
        weak: "{{ unowned_files.stdout != '' }}"
    
    - debug:
        var: weak
      
    - block:
        - debug:
            msg: 해당없음
        - set_fact:
            result: "{{ {'num': num, 'diag': diag, 'weak': none, 'reason': ['N/A']} }}"
        - copy:
            content: "{{ result | to_nice_json }}"
            dest: /home/ubuntu/grbprj/log/linux/diag/6.json
          delegate_to: localhost
      when: weak is none

    - block:
        - debug:
            msg: 취약
        - set_fact:
            result: "{{ {'num': num, 'diag': diag, 'weak': True, 'reason': ['Files and directories exist without an assigned user and group'], 'how_action': ['Action will delete files or directories without an assigned user and group. If necessary, you can change the user and group of the file and directory. Do you want to proceed?']} }}"
        - copy:
            content: "{{ result | to_nice_json }}"
            dest: /home/ubuntu/grbprj/log/linux/diag/6.json
          delegate_to: localhost
      when: weak is not none and weak

    - block:
        - debug:
            msg: 양호
        - set_fact:
            result: "{{ {'num': num, 'diag': diag, 'weak': False, 'reason': ['Files and directories exist with an assigned user and group']} }}"
        - copy:
            content: "{{ result | to_nice_json }}"
            dest: /home/ubuntu/grbprj/log/linux/diag/6.json
          delegate_to: localhost
      when: weak is not none and not weak

