# /etc/passwd 파일 소유자 및 권한 설정_check
---
- name: checklist 7
  hosts: intranetweb
  tasks: 
# header

  - set_fact:
      diag: Check /etc/passwd file owner and permission
      num: 7

  - debug:
      var: diag
  - debug:
      var: num

# body
  - name: Check owner and permissions of /etc/passwd
    command: ls -l /etc/passwd
    register: passwd_file_info

# checking weak
  - set_fact:
      weak: not (passwd_file_info.stdout.split()[2] == 'root' and passwd_file_info.stdout.split()[0] == '-rw-r--r--.')
    
  - debug:
      var: weak

# result
  - block:
      - debug:
          msg: 해당없음
      - set_fact:
          result: "{{ {'num': num, 'diag': diag, 'weak': none, 'reason': ['N/A']} }}"
      - copy:
          content: "{{ result | to_nice_json }}"
          dest: /home/ubuntu/grbprj/log/linux/diag/7.json
        delegate_to: localhost
    when: weak is none

  - block:
      - debug:
          msg: 취약
      - set_fact:
           result: "{{ {'num': num, 'diag': diag, 'weak': True, 'reason': ['Owner of /etc/passwd file is not root or permissions are set over 644'], 'how_action': ['Action will change the owner and permissions of the /etc/passwd file. Do you want to proceed?']} }}"
      - copy:
          content: "{{ result | to_nice_json }}"
          dest: /home/ubuntu/grbprj/log/linux/diag/7.json
        delegate_to: localhost
    when: weak is not none and weak

  - block:
      - debug:
          msg: 양호
      - set_fact:
          result: "{{ {'num': num, 'diag': diag, 'weak': False, 'reason': ['The owner of the /etc/passwd file is root, and the permission is set to 644 or less']} }}"
      - copy:
          content: "{{ result | to_nice_json }}"
          dest: /home/ubuntu/grbprj/log/linux/diag/7.json
        delegate_to: localhost
    when: weak is not none and not weak

